### ISSUE TITLE
請教大佬Gemini能設定safety嗎

### ISSUE THREAD

**Issue by zhao-ng327** [vacuityv/ai-java-sdk#10]
我翻了一下原碼是不是沒法改啊

**Comment by vacuityv** [comment]
@zhao-ng327  是可以设定 safety 的，ChatRequest 里面有 safetySettings 的变量

**Comment by zhao-ng327** [comment]
我不是很確定怎麼用
![image](https://github.com/vacuityv/ai-java-sdk/assets/61046297/0324714a-3a58-4094-a013-9bf691c0feb2)
![image](https://github.com/vacuityv/ai-java-sdk/assets/61046297/697649e7-228f-4e8d-9ee1-0eefab5ec2b6)
建立完request之後會報錯
![image](https://github.com/vacuityv/ai-java-sdk/assets/61046297/97decb32-f89b-438e-9c7d-e3ce32af439e)

**Comment by vacuityv** [comment]
@zhao-ng327  我明天测试下再给你反馈

**Comment by zhao-ng327** [comment]
> @zhao-ng327  我明天测试下再给你反馈

麻煩了，感謝！

**Comment by vacuityv** [comment]
@zhao-ng327  抱歉，前面是因为一个bug导致的，你可以使用最新的1.7.7版本：

```java
List<ChatRequest.SafetySetting> safetySettings = new ArrayList<>();
        safetySettings.add(new ChatRequest.SafetySetting(HarmCategory.HARM_CATEGORY_HATE_SPEECH.toString(), HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE.toString()));
        
ChatRequest request = ChatRequest.builder()
         .contents(messages)
         .safetySettings(safetySettings)
         .build();
```

**Comment by zhao-ng327** [comment]
沒問題了 感恩
