### ISSUE TITLE
gemini似乎更新了api，

### ISSUE THREAD

**Issue by fantasyjqc** [vacuityv/ai-java-sdk#12]
近期谷歌好像更新了api，有些配置项不能用了，报错如图：

![image](https://github.com/user-attachments/assets/53e93feb-d4fc-4811-9f20-3b477c8a1197)

VacSdkException(code=-1, msg=error, details=[ChatResponseError(error=ChatResponseError.ChatResponseErrorDetail(code=400, message=User location is not supported for the API use., status=FAILED_PRECONDITION))])

大佬有空的时候帮忙看看。

**Comment by vacuityv** [comment]
@fantasyjqc  这错误是说你的请求地理位置不对，Google不支持大陆和香港的ip请求

**Comment by fantasyjqc** [comment]
> @fantasyjqc 这错误是说你的请求地理位置不对，Google不支持大陆和香港的ip请求

sorry是我的问题，看成是user这个role不正确了/(ㄒoㄒ)/~~
