### ISSUE TITLE
gemini stream output Can't see the effect

### ISSUE THREAD

**Issue by ticktack** [vacuityv/ai-java-sdk#2]
gemini stream output Can't see the effect.  waiting for seconds did it take to get out all at once?

**Comment by vacuityv** [comment]
@ticktack  什么意思，你是怎么使用的呢

**Comment by ticktack** [comment]
按流式的方式用的：
GeminiClient client = new GeminiClient(AIConstant.GEMINI_KEY, Duration.ofSeconds(100), AIConstant.GEMINI_BASE_API);
        List<ChatMessage> messages = new ArrayList<>();
        messages.add(new ChatMessage("user", "帮我用Java写一个快速排序算法"));
        me.vacuity.ai.sdk.gemini.request.ChatRequest.GenerationConfig generationConfig = new me.vacuity.ai.sdk.gemini.request.ChatRequest.GenerationConfig();
        generationConfig.setMaxOutputTokens(4096);
        generationConfig.setTopK(1);
        generationConfig.setTopP(1);
        generationConfig.setTemperature(0.9f);
        ChatRequest request = ChatRequest.builder()
                .contents(messages)
                .generationConfig(generationConfig)
                .build();
        try {
            Flowable<StreamChatResponse> response = client.streamChat(request);
            response.doOnNext(s -> {
                System.out.println(s.getText());
                System.out.println("================================================");
            }).blockingSubscribe();
        } catch (VacSdkException e) {
            if (e.getDetails() != null) {
                System.out.println(e.getDetails().get(0).getError().getMessage());
            }
        }

**Comment by vacuityv** [comment]
@ticktack  你是用了别人转的api地址吗，我这边测试很正常，是不是你那个自定义base的问题

**Comment by ticktack** [comment]
没问题哦，反向代理的地址

**Comment by vacuityv** [comment]
方便地址给我测试下吗

**Comment by ticktack** [comment]
加微信发你哈 ticktack2011
